sudo: required
dist: xenial
language: node_js
node_js:
  - '11'

cache:
  directories:
    - node_modules

before_install:
  - export TZ=Europe/Amsterdam
  - date

install:
  - npm install
  - npm run build
script:
  - npm run test

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never

deploy:
  provider: npm
  email: ewelina@thehyve.nl
  api_key:
    secure: qvNVRub3ZdXJ9ele7jvWMrWlca1LtxnDgbBah0FnkN5CKJ5pnyK0dxoQc3JOS3LBZi5BjQmhoXV0kSPYiRWIHvtHQfLrAffLhQ4cVJVd4nhCkHF1DSFwGBB9zUFanNJabpZzKNDBhsLkfRzedKI05+AYvihEFVj6y0DYwhgZ6Jj3tGJ8MpQHWKDePWWvtrEpQFOggc6KMNMTfRsVW1UF9xysfcIkZkZG961VEOz/jMScwq5LWhs+iFUZBrhUjSzdAkv3wDDXHzF5p1jujoISSY3HvUixmrPge1ALETDiYWCvUlMOsJXkCpNYxt+CEvZ1eWoC1ldzptBdDdPUCjFiAiyGKzCIJ8K3nQo4SlzC2cvMQtzR1bZRotXtz6aWILD+MgKMpJtCjl5gdkiYv9R75glsrrn3CRsIzjE1q9iPU2GffRzbGI0S8dx8s3ZnveSMb3527s4yWC9/rdk4RZ7s+Y2ztEdX2invwUT2jIHfn618IaKhu9Qxfl4roMiPtcc8quMGDAz2gPKGuzrVBYSSZVkS4YzbCOG3ihFyuPGBsUB4TIhnjLlhPATx4l7tCtCOy+w6iuDPA4xA1htLALDUGgYGYwkiLqTOSmQkMSQiOMb7uALZdAUmnit4J4c7pZHScLrKs9vlqmelBh6CjFosNCTREOWIm7JM2cAnttVOZU0=
  on:
    tags: true
    repo: thehyve/Fractal.js
    branch: dev
