sudo: required
dist: xenial
language: node_js
node_js:
  - '11'

cache:
  directories:
    - node_modules

before_install:
  - export TZ=Europe/Amsterdam
  - date

install:
  - npm install
  - npm run build
script:
  - npm run test

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
