sudo: required
dist: xenial
language: node_js
node_js:
  - '11'

cache:
  directories:
    - node_modules

before_install:
  - export TZ=Europe/Amsterdam
  - date

install:
  - npm install
  - npm run build
script:
  - npm run test

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never

deploy:
  provider: npm
  email: ewelina@thehyve.nl
  api_key:
    secure: DgROzrmm6vxoYTvuBVITZ/7bjSuelFDOi1DnZ3rNO8X5SgXiG26l5zyaBPvtnnlMy/iA8ABbedFJDfpBzD5kc7fJ8ZIUOBdjCwWhvB25MNw5dwjffhTgT+eiOGaFBIpHyTMwkhMVabiR2U7U/MXRWo3ttns7FKT2SNk7iL1slsM5DUPi+t9WoVsHL+kKqD+fv8Y5pg6ETsufUvGMvxZD3wnI/KA7Le/YEV6vRDwg4FE6mBIVK/IiW79iGCdWkt33QcjdmuZsXPrsz5QGNhIxx198dOk9MLsSyzsNIBq/8HsDfWC/tScXFUVxNMOOx3NQdjwXrZsFiyvmRPPEqbz63kBQc+LlL3ID+v1FIjKIWlKZvwpA9W1sluY5iHytDs4oPgwLHgEgXKBaMRjDIc2VfY5SCsGcI/EvPxiESEBaSGRnPhEvVdI2wYAW19TX93exfRQVmIVMxS1Wo9OoRMSj9ozSxI2y/eo/jZDA8L89hpNTWt6RmsNfFJU+oMoqaGKerZ/bBcuOhm3UGyit4RcHhBu7WNAmTXIXxAV6EFZitRAVSHDzebIMh8ADWsQJWE75XciqGtc+uXOOCVzasfazMTCWq7cli9qUe+W9hb8Z/irfHDQdXu9ROSPGJbzQnifQVq5xb5FhxqkmLAnko7rgV8Ky+N4mgUvulK8S/dSMLms=
  on:
    tags: true
    repo: thehyve/Fractal.js
    branch: dev
